demo purpose20

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -12,10 +12,7 @@ jobs:
     
     outputs:
       output1: ${{ steps.package.outputs.test }}
-   
-   
-   
-  
+ 
     steps:
       - uses: actions/checkout@v1
       - name: Set up JDK 8
@@ -29,26 +26,22 @@ jobs:
       - name: Run command
         run: mvn clean test "-DconfigPath=qa.yaml" "-Dtags=@updatePetDetailsById"
      
-     
-        
-  display:
-    runs-on: windows-latest 
-    
-    outputs:
-      output1: ${{ steps.package.outputs.test }}
+      - name: Pare Integration Test Results
+        id: Parse Result
+        run: |
+         $resultsFile = 'results-json.txt'
+         $resultPath = './target/surefire-reports/results-json.txt'
+         $resultJson = Get-Content $resultPath | ConvertFrom-Json -Depth 4
+         $testFailures = $resultJson.failed
+         echo "testFailures=$testFailures" | out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
+         if(($resultPath) -and ($testFailures -ge 1)){
+         Write-Output "`n"
+         Write-Error "Due to ($testFailures) Failed Tests, the workflow is exiting and a Jira Bug is being created.`n" "
+         exit 1
+         }
+         echo "$testFailures"
   
-    steps:
-      - uses: actions/checkout@v1
-      - name: Set up JDK 8
-        uses: actions/setup-java@v1
-        with:
-          java-version: '1.8'
-          
-      - name: Build with Maven
-        run: mvn -B package --file pom.xml
-        
-      - name: Run command
-        run: mvn clean test "-DconfigPath=qa.yaml" "-Dtags=@updatePetDetailsById"
+  
      
        
  
